//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zanovo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialConsumptions
    {
        public int ID_Consumption { get; set; }
        public int ID_Production { get; set; }
        public int ID_Material { get; set; }
        public decimal Actual_Quantity { get; set; }
    
        public virtual Materials Materials { get; set; }
    }
}
