//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zanovo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialPrices
    {
        public int ID_Price { get; set; }
        public int ID_Material { get; set; }
        public decimal Price { get; set; }
    
        public virtual Materials Materials { get; set; }
    }
}
