//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zanovo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItems
    {
        public int ID_Item { get; set; }
        public int ID_Order { get; set; }
        public int ID_Product { get; set; }
        public decimal Quantity { get; set; }
        public decimal Price_Per_Unit { get; set; }
        public decimal Line_Sum { get; set; }
    
        public virtual Orders Orders { get; set; }
        public virtual Products Products { get; set; }
    }
}
