//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zanovo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionItems
    {
        public int ID_Item { get; set; }
        public int ID_Production { get; set; }
        public int ID_Product { get; set; }
        public decimal Quantity_Produced { get; set; }
    
        public virtual Productions Productions { get; set; }
        public virtual Products Products { get; set; }
    }
}
