//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zanovo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecItems
    {
        public int ID_Item { get; set; }
        public int ID_Spec { get; set; }
        public int ID_Material { get; set; }
        public decimal Quantity_Per_Unit { get; set; }
    
        public virtual Materials Materials { get; set; }
    }
}
