//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zanovo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int ID_User { get; set; }
        public int ID_Role { get; set; }
        public string Login { get; set; }
        public string Password_Hash { get; set; }
        public bool Is_Blocked { get; set; }
        public int Failed_Attempts { get; set; }
    
        public virtual Roles Roles { get; set; }
    }
}
